
<table id="list" class="table table-hover table-striped">
<thead>
    <tr>
        <th class="col-xs-7">Nome</th>
        <th class="col-xs-4">Crédito</th>
        <th class="col-xs-1"><a href="<?php echo $this->losUrl()->from('cliente/add',[],true)?>" class="btn btn-sm btn-success pull-right"><?= $this->losIcon('glyphicon-plus') ?></a></th>
    </tr>
</thead>
<tbody>
    <?php foreach ($this->paginator as $entity):?>
        <tr class="linha">
            <td><?= $entity->getNome()?></td>
            <td><?= $entity->getCredito()?></td>
            <td class="text-right">
                <a href="<?php echo $this->losUrl()->from('cliente/edit',['id'=>$entity->getId()], true)?>" class="btn btn-xs btn-warning"><?= $this->losIcon('glyphicon-edit') ?></a>
                <a href="<?php echo $this->losUrl()->from('cliente/delete',['id'=>$entity->getId()], true)?>" class="btn btn-xs btn-danger"><?= $this->losIcon('glyphicon-trash') ?></a>
            </td>
        </tr>
    <?php endforeach;?>
</tbody>
</table>

<?php if ($this->paginator->count() > 1):?>
<div class="row">
    <div class="col-xs-12 text-center"><?= $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
